language: java
jdk: 
  - oraclejdk8
  - oraclejdk9
  - openjdk8
os: windows

branches:
  only:
    - master
    - develop
cache:
  directories:
    - $HOME/.m2/repository

notifications:
  email:
    - zuf999@mail.ru

script: 
  - mvn clean install

